version: '3.9'

services:
  backend-app:
    build: .
    container_name: backend_app
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://localhost:5432/online_store
      DB_USER: postgres
      DB_PASSWORD: postgre
    ports:
      - "8080:8080"

  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: online_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432"
    volumes:
      - .src/main/resources/sql:/docker-entrypoint-initdb.d