version: '3.9'

services:
  app:
    build: .
    environment:
      DB_HOST: jdbc:postgresql://db:5432/online_store
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dl
    ports:
      - "5432:5432"