version: '3.9'

services:
  api:
    build: .
    container_name: api
    depends_on:
      - database
    environment:
      - DATABASE_HOSTNAME=database
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    image: api:1.0.0
    ports:
      - "8081:8081"

  database:
    container_name: database
    environment:
      POSTGRES_DB: online_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - .src/main/resources/sql:/docker-entrypoint-initdb.d