version: '3.9'

services:
  api:
    build: ../FinalTask3
    container_name: api
    depends_on:
      - database
    environment:
      - DATABASE_HOSTNAME=database
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - MAIL_USERNAME=foronlinestoretestpurposes
      - MAIL_PASSWORD=cktp mtvp lhpy mgvv
    image: api:latest
    ports:
      - "8081:8081"

  database:
    container_name: database
    environment:
      POSTGRES_DB: online_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ../FinalTask3/src/main/resources/sql:/docker-entrypoint-initdb.d
      - ./src/main/resources/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./src/main/resources/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

  frontend:
    build: ../frontend
    container_name: frontend
    depends_on:
      - api
    ports:
      - "4200:4200"
    volumes:
      - ../frontend:/app

  pgadmin:
    container_name: dbms
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    image: dpage/pgadmin4
    ports:
      - "5050:80"

  sonarqube:
    container_name: sonarqube
    depends_on:
      - api
    environment:
      - SONARQUBE_JDBC_HOSTNAME=database
      - SONARQUBE_JDBC_USERNAME=postgres
      - SONARQUBE_JDBC_PASSWORD=postgres
    image: sonarqube:latest
    ports:
      - "9000:9000"

  mkdocs:
    build:
      context: ../mkdocs
    container_name: mkdocs
    ports:
      - "8000:8000"