version: '3.9'

services:
  backend-app:
    build:
      context: .
    container_name: backend_app
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/online_store
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8081:8081"

  db:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: online_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - .src/main/resources/sql:/docker-entrypoint-initdb.d